### ISSUE TITLE
E254: Cannot allocate color NONG

### ISSUE THREAD

**Issue by amerixan** [phucngodev/mono#1]
I believe there is a typo in mono.vim on line 25:

```
ctermfg  = grey ctermbg=239 guifg=NONG
```

`NONG` should be `NONE`.

**Comment by phucngodev** [comment]
Thanks @amerixan for report it. I've just corrected the typo and pushed the fix.

**Comment by amerixan** [comment]
Thanks, can confirm the fix.  Looks nice!
